import Head from 'next/head';
import HeadChat from '../components/HeadChat';
import ContentChat from '../components/ContentChat';

export default function Home() {
  return (
    <div>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeadChat />

      <ContentChat />

    </div>
  )
}
